Add sonarqube pack
hashicorp/nomad-pack-community-registry pull request #104
Opened 2022-01-15 13:10 UTC by ferhatvurucu

2022-01-15 13:10 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/nomad-pack-community-registry?pullRequest=104)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/nomad-pack-community-registry?pullRequest=104)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/nomad-pack-community-registry?pullRequest=104).</sub>

2022-01-19 04:46 UTC, RickyGrassmuck commented
I used to have the pleasure of maintaining a Sonarqube deployment on Nomad and wanted to point out that Sonarqube requires the system it runs on to have a couple of `sysctl` values set to levels that are higher than the system defaults(at least for Ubuntu 20.04 and Centos 7). Just looked at our client servers configuration and we had to have the following `sysctl` values set in order for the application to startup.

```
vm.max_map_count=262144
fs.file-max=65536
```

It's been a while since we stopped using Sonarqube so this may have changed but it's likely worth adding a note/warning in the README about the possibility of needing to change system level settings on the clients the job is going to be scheduled on.

2022-01-19 08:10 UTC, ferhatvurucu commented
> I used to have the pleasure of maintaining a Sonarqube deployment on Nomad and wanted to point out that Sonarqube requires the system it runs on to have a couple of `sysctl` values set to levels that are higher than the system defaults(at least for Ubuntu 20.04 and Centos 7). Just looked at our client servers configuration and we had to have the following `sysctl` values set in order for the application to startup.
> 
> ```
> vm.max_map_count=262144
> fs.file-max=65536
> ```
> 
> It's been a while since we stopped using Sonarqube so this may have changed but it's likely worth adding a note/warning in the README about the possibility of needing to change system level settings on the clients the job is going to be scheduled on.

I updated the client requirements. Thanks a lot for the contribution.

2022-02-18 08:09 UTC, jrasell requested changes
Hi @ferhatvurucu, this looks great and works really well thanks! I have a couple of minor comments that I would like to get addressed before merging.

2022-02-18 08:09 UTC, jrasell commented on packs/sonarqube/README.md
> +- If you're running on Linux, you must ensure to set these values by running the following commands as root:
Would you be able to expand on why we need these values so future readers can get context on why they are needed?

2022-02-18 08:09 UTC, jrasell commented on packs/sonarqube/variables.hcl
> +  default = "sonarqube"
```suggestion
  description = "The name to use as the job name which overrides using the pack name."
  type        = string
  default     = "sonarqube"
```

2022-02-18 08:09 UTC, jrasell commented on packs/sonarqube/templates/sonarqube.nomad.tpl
> +      mode = "fail"
```suggestion
      attempts = 2
      interval = "5m"
      delay    = "15s"
      mode     = "fail"
```

2022-02-19 16:27 UTC, ferhatvurucu commented
Hi @jrasell,

Thanks a lot for your review and contribution. I updated the pack based on your comments.

2022-02-21 08:53 UTC, jrasell approved these changes
LGTM, thanks @ferhatvurucu!

2022-02-21 08:53 UTC, merged