[wip] introducing plugins and jasc_config variables
hashicorp/nomad-pack-community-registry pull request #81
Opened 2021-11-04 23:19 UTC by attachmentgenie

and adding nomad cloud example

2021-11-04 23:22 UTC, attachmentgenie commented
still trying to workout why this example crashes jenkins upon starting a worker in nomad and why [qa.nomad](https://github.com/attachmentgenie/nomad-jobs/blob/master/qa.nomad) doesnt

2021-11-05 08:12 UTC, efbar commented on packs/jenkins/vars_cloud.nomad
> +      nomadUrl: "http://{{ env "attr.unique.network.ip-address" }}:4646"
here I would add the consul service variant, if the job is registering itself to consul.

2021-11-05 08:12 UTC, efbar commented on packs/jenkins/vars_cloud.nomad
> +                        "JENKINS_URL": "http://{{ env "NOMAD_ADDR_http" }}",
here too.

2021-11-05 08:41 UTC, attachmentgenie commented
@efbar good point again. i decided in the end to create a much simpler jasc example and will move the nomad cloud workers into a separate PR. It will take me a while to figure out what is going wrong, and i want this to move forward

2021-11-08 11:10 UTC, DerekStrickland commented
Hi @attachmentgenie  

This looks like it has merge conflicts with the current main. Since you are closer to this code, do you mind taking a look and resolving?

2021-11-08 11:11 UTC, DerekStrickland requested changes
Merge conflicts detected. Sorry if I caused this by merging the chown PR.  Could you resolve and let me know? I'd love to get this in.

2021-11-11 22:16 UTC, DerekStrickland approved these changes
It's working great after the merge. Thanks so much for this contribution!

2021-11-11 22:16 UTC, merged